name: E2E Playwright CI

on:
  pull_request:
    paths:
      - "moderato-ui/**"

defaults:
  run:
    working-directory: moderato-ui

jobs:
  playwright:
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [14.17.0]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: Node_modules install
        run: yarn

      - name: E2E test
        run: yarn test
        # envはこのアクション（name: E2E test.）のみで有効
        env:
          LOCAL_PUBLIC_URL: http://localhost:3000

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
