name: E2E CI

on:
  pull_request:
    paths:
      - "moderato-ui/**"

jobs:
  playwright:
    timeout-minutes: 60

    strategy:
      matrix:
        node-version: [14.17.0]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache-node-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-

      - name: E2E test.
        working-directory: e2e
        run: |
          yarn 
          yarn test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
