name: Frontend eslint CI

on:
  pull_request:
    paths:
      - "moderato-ui/**"

defaults:
  run:
    working-directory: moderato-ui

jobs:
  eslint:
    timeout-minutes: 5
    # https://ema-hiro.hatenablog.com/entry/2020/12/15/123210
    # 変数置換できるようになるため一つのファイルで複数version対応可能になる
    strategy:
      matrix:
        node-version: [14.17.0]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: moderato-ui/yarn.lock

      # - name: Cache node_modules
      #   uses: actions/cache@v1
      #   id: cache-node-modules
      #   with:
      #     path: ~/.cache/yarn
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      #       ${{ runner.os }}-

      - name: eslint check
        # working-directory: moderato-ui
        run: |
          yarn
          yarn eslint
