name: Frontend CI eslint

on:
  pull_request:
    paths:
      - 'moderato-ui/**'

jobs:
  eslint:

    # https://ema-hiro.hatenablog.com/entry/2020/12/15/123210
    # 変数置換できるようになるため一つのファイルで複数version対応可能になる
    strategy:
      matrix:
        node-version: [14.17.0]
        os: [ubuntu-22.04]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v1
      id: cache-node-modules
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
          ${{ runner.os }}-

    - name: eslint check
      working-directory: frontend
      run: |
        yarn
        yarn eslint
